version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://takuakiazuma:KyotanabePickle@db:5432/event_manager
      - SECRET_KEY=your_very_secret_key_here # セキュリティ上の理由から、本番環境では環境変数から取得する必要があります。
    depends_on:
      - db
    command: >
      sh -c "flask db upgrade &&
             gunicorn --bind 0.0.0.0:5000 app:app"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=takuakiazuma
      - POSTGRES_PASSWORD=KyotanabePickle
      - POSTGRES_DB=event_manager
    ports:
      - "5432:5432"

volumes:
  postgres_data: